# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Xuefei's Blog
tagline:          'personal website'
description:      'Neuroscience / Coding / Climbing  @ Computer Science Major, Fudan University'
url:              http://xuefe-wang.github.io
baseurl:          /

author:
  name:           'Xuefei Wang'
  github:         xuefei-wang
  twitter:        xuefei_w
  email:          wang.xuefei.wang@gmail.com

paginate:         5

