# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Xuefei Wang
tagline:          'personal website'
description:      'Neuroscience / Coding / Climbing'
url:              http://xuefe-wang.github.io
baseurl:          /

author:
  name:           'Xuefei Wang'
  github:         xuefei-wang
  twitter:        xuefei_w
  email:          wang.xuefei.wang@gmail.com

paginate:         5


excerpt_separator: "<!--more-->"
